[package]
name = "rtiow"
version = "0.1.0"
authors = ["Markus Klein <markus-klein@live.de>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
structopt = "0.3.14"
image = "0.23.5"
indicatif = "0.14.0"
rayon = "1.3.0"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 16
